version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      eslint:
        dependency-type: "development"
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      commitlint:
        dependency-type: "development"
        patterns:
          - "@commitlint/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      semantic-release:
        dependency-type: "development"
        patterns:
          - "semantic-release"
          - "@semantic-release/*"
          - "conventional-changelog-conventionalcommits"
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
